name: "ğŸ§œ Generate Mermaid Diagrams"

on:
  push:
    branches:
      - main
    paths:
      - "**.mmd"
  pull_request:
    paths:
      - "**.mmd"

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "ğŸ“ Get changed files"
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.md
            **.mmd

      - name: "ğŸ§œ Generate Mermaid diagrams"
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: uni-3/render-mermaid-svg@v2
        with:
          input-files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: "ğŸ“ Commit rendered svg files"
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: "*.svg"
          commit_message: "chore: generate mermaid diagrams"
